# Generated by Django 2.0.5 on 2018-05-08 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inferencetags',
            options={'verbose_name': 'Inference Tag', 'verbose_name_plural': 'Inference Tags'},
        ),
        migrations.AlterModelOptions(
            name='inferencetotagmap',
            options={'verbose_name': 'Inference To Tag Map', 'verbose_name_plural': 'Inferences To Tags Map'},
        ),
        migrations.AlterModelOptions(
            name='tagmodifiers',
            options={'verbose_name': 'Tag Modifier', 'verbose_name_plural': 'Tag Modifiers'},
        ),
        migrations.AlterModelOptions(
            name='trainingtags',
            options={'verbose_name': 'Training Tag', 'verbose_name_plural': 'Training Tags'},
        ),
    ]
